Secrets:
kubectl get secrets
kubectl create secret generic --help
kubectl create secret generic mysql --from-literal=password=root
kubectl get secrets mysql -o yaml
kubectl create secret generic --app-name  --from-literal=
kubectl create secret generic --app-name  --from-file=
kubectl create -f file_path


Create secret with several keys: 
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
 name: mysecret
type: Opaque
data:
 password: $(echo "admin_test" | base64)
 username: $(echo "admin"| base64)
EOF



Secret Encoding and Decoding : 
for encode and decode 
echo -n "value" | base64
echo -n "base64value" | base64 --decode

if we have secrets and its values and can use envForm with secretRef:
envFrom:
  - secretRef:
      name: app-secret