Service Accounts:
kubectl get serviceaccounts
kubectl get serviceaccount/[serviceaccount_name] 
kubectl get serviceaccounts admin-user -o yaml


Creating & Checking with service account and secret: 
kubectl create serviceaccount test
kubectl get serviceaccounts test -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  # ...
secrets:
- name: test-token-w3scr

and check that token: 
kubectl get secret test-token-w3scr -o yaml 


Clean Up : 
kubectl delete serviceaccount/admin-user



Create service account with pod: 
apiVersion: v1
kind: Pod
metadata:
  name: cicd
spec:
  serviceAccount: cicd
  containers:
  - image: nginx
    name: cicd